name: Checks
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
