name: Checks
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
